# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  nodeVersion: '18.x'
  backendDirectory: 'backend'
  frontendDirectory: 'frontend'

steps:
  # Install Node.js once for all tasks
  - task: NodeTool@0
    inputs:
      versionSpec: '$(nodeVersion)'
    displayName: 'Install Node.js $(nodeVersion)'

  # Backend Test Phase
  - script: |
      cd $(backendDirectory)
      npm ci
    displayName: 'Backend - Install Dependencies'

  - script: |
      cd $(backendDirectory)
      npm run lint
    displayName: 'Backend - Lint'
    continueOnError: true

  - script: |
      cd $(backendDirectory)
      npm test
    displayName: 'Backend - Run Tests'

  # Frontend Test Phase
  - script: |
      cd $(frontendDirectory)
      npm ci
    displayName: 'Frontend - Install Dependencies'

  - script: |
      cd $(frontendDirectory)
      npm run lint
    displayName: 'Frontend - Lint'
    continueOnError: true

  # Backend Build Phase
  - script: |
      cd $(backendDirectory)
      npm run build
    displayName: 'Backend - Build'
    condition: succeeded()

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(backendDirectory)/dist'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/backend.zip'
      replaceExistingArchive: true
    displayName: 'Archive Backend Files'
    condition: succeeded()

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/backend.zip'
      ArtifactName: 'backend'
      publishLocation: 'Container'
    displayName: 'Publish Backend Artifact'
    condition: succeeded()

  # Frontend Build Phase
  - script: |
      cd $(frontendDirectory)
      npm run build
    displayName: 'Frontend - Build'
    condition: succeeded()

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(frontendDirectory)/.next'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/frontend.zip'
      replaceExistingArchive: true
    displayName: 'Archive Frontend Files'
    condition: succeeded()

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/frontend.zip'
      ArtifactName: 'frontend'
      publishLocation: 'Container'
    displayName: 'Publish Frontend Artifact'
    condition: succeeded()