# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- dev

pool:
  name: 'Windows (BENJAMIN)'

variables:
  backendNodeVersion: '18.x'
  frontendNodeVersion: '18.x'
  backendDirectory: 'backend'
  frontendDirectory: 'frontend'

stages:
- stage: Test
  displayName: 'Run Tests'
  jobs:
  - job: BackendTests
    displayName: 'Backend Tests'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '$(backendNodeVersion)'
      displayName: 'Install Node.js $(backendNodeVersion)'

    - script: |
        cd $(backendDirectory)
        npm install
      displayName: 'Backend - npm install'

    - script: |
        cd $(backendDirectory)
        npm run lint
      displayName: 'Backend - Lint'
      continueOnError: true

    - powershell: |
        $serverJob = Start-Process -FilePath "npm" -ArgumentList "run", "dev" -WorkingDirectory "$(System.DefaultWorkingDirectory)/$(backendDirectory)" -PassThru -NoNewWindow
        Write-Host "Started backend server with PID: $($serverJob.Id)"
        
        # Wait for server to start
        Write-Host "Waiting 15 seconds for server to start..."
        Start-Sleep -Seconds 15
        
        # Store the PID in a variable that can be accessed by subsequent tasks
        Write-Host "##vso[task.setvariable variable=ServerPID]$($serverJob.Id)"
      displayName: 'Start Backend Server'

    - script: |
        cd $(backendDirectory)
        npm test
      displayName: 'Backend - Run tests'

    - powershell: |
        # Kill the process using the PID we saved earlier
        $serverPID = $(ServerPID)
        Write-Host "Stopping backend server with PID: $serverPID"
        
        if ($serverPID) {
            try {
                Stop-Process -Id $serverPID -Force -ErrorAction SilentlyContinue
                Write-Host "Process stopped successfully"
            } catch {
                Write-Host "Error stopping process: $_"
            }
        }
        
        # As a backup, attempt to kill all node processes related to our backend
        Write-Host "Attempting to stop any remaining node processes for backend..."
        Get-Process -Name "node" -ErrorAction SilentlyContinue | 
            Where-Object {$_.Path -like "*$(backendDirectory)*" -or $_.CommandLine -like "*$(backendDirectory)*"} | 
            ForEach-Object {
                Write-Host "Stopping process with ID: $($_.Id)"
                Stop-Process -Id $_.Id -Force -ErrorAction SilentlyContinue
            }
      displayName: 'Stop Backend Server'
      condition: always()

  - job: FrontendTests
    displayName: 'Frontend Tests'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '$(frontendNodeVersion)'
      displayName: 'Install Node.js $(frontendNodeVersion)'

    - script: |
        cd $(frontendDirectory)
        npm install
      displayName: 'Frontend - npm install'

    - script: |
        cd $(frontendDirectory)
        npm run lint
      displayName: 'Frontend - Lint'
      continueOnError: true

- stage: Build
  displayName: 'Build Applications'
  dependsOn: Test
  jobs:
  - job: BuildBackend
    displayName: 'Build Backend'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '$(backendNodeVersion)'
      displayName: 'Install Node.js $(backendNodeVersion)'

    - script: |
        cd $(backendDirectory)
        npm install
      displayName: 'Backend - npm install'

    - script: |
        cd $(backendDirectory)
        npm run build
      displayName: 'Backend - Build'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(backendDirectory)/dist'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/backend.zip'
        replaceExistingArchive: true
      displayName: 'Archive backend files'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/backend.zip'
        ArtifactName: 'backend'
        publishLocation: 'Container'
      displayName: 'Publish backend artifact'

  - job: BuildFrontend
    displayName: 'Build Frontend'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '$(frontendNodeVersion)'
      displayName: 'Install Node.js $(frontendNodeVersion)'

    - script: |
        cd $(frontendDirectory)
        npm install
      displayName: 'Frontend - npm install'

    - script: |
        cd $(frontendDirectory)
        npm run build
      displayName: 'Frontend - Build'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(frontendDirectory)/.next'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/frontend.zip'
        replaceExistingArchive: true
      displayName: 'Archive frontend files'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/frontend.zip'
        ArtifactName: 'frontend'
        publishLocation: 'Container'
      displayName: 'Publish frontend artifact'